import { UserRole } from "../constants/roles";
import { Permission } from "../constants/permissions";

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  SUPER_ADMIN: [
    "dashboard:view",
    "employees:view",
    "employees:create",
    "employees:update",
    "employees:delete",
    "departments:view",
    "departments:create",
    "departments:update",
    "teams:view",
    "teams:create",
    "teams:update",
    "projects:view",
    "projects:create",
    "projects:update",
    "tasks:view",
    "tasks:create",
    "tasks:update",
    "tasks:delete",
    "tasks:assign",
    "reports:view",
    "audit_logs:view",
    "settings:view",
    "settings:update",
    "roles:view",
    "roles:manage",
  ],
  ADMIN: [
    "dashboard:view",
    "employees:view",
    "employees:create",
    "employees:update",
    "employees:delete",
    "departments:view",
    "departments:create",
    "departments:update",
    "teams:view",
    "teams:create",
    "teams:update",
    "projects:view",
    "projects:create",
    "projects:update",
    "tasks:view",
    "tasks:create",
    "tasks:update",
    "tasks:delete",
    "tasks:assign",
    "reports:view",
    "audit_logs:view",
    "settings:view",
  ],
  MANAGER: [
    "dashboard:view",
    "employees:view",
    "employees:create",
    "employees:update",
    "employees:delete",
    "departments:view",
    "teams:view",
    "projects:view",
    "tasks:view",
    "tasks:create",
    "tasks:update",
    "tasks:delete",
    "tasks:assign",
    "reports:view",
    "audit_logs:view",
    "settings:view",
  ],
  TEAM_LEAD: [
    "dashboard:view",
    "employees:view",
    "tasks:view",
    "tasks:create",
    "tasks:update",
    "tasks:assign",
  ],
  EMPLOYEE: [
    "dashboard:view",
    "employees:view",
    "tasks:view",
    "tasks:update",
  ],
  VIEWER: [
    "dashboard:view",
    "employees:view",
    "tasks:view",
    "projects:view",
    "reports:view",
  ],
};

export function hasPermission(role: UserRole, permission: Permission): boolean {
  const permissions = ROLE_PERMISSIONS[role];
  return permissions ? permissions.includes(permission) : false;
}
