import { UserRole } from "../constants/roles";
import { Permission } from "../constants/permissions";

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  SUPER_ADMIN: [
    "view:dashboard",
    "view:employees",
    "create:employees",
    "edit:employees",
    "delete:employees",
    "view:departments",
    "create:departments",
    "edit:departments",
    "view:teams",
    "create:teams",
    "edit:teams",
    "view:projects",
    "create:projects",
    "edit:projects",
    "view:tasks",
    "create:tasks",
    "edit:tasks",
    "delete:tasks",
    "edit:task_status",
    "view:reports",
    "view:audit_logs",
    "view:settings",
    "edit:settings",
    "export:data",
  ],
  ADMIN: [
    "view:dashboard",
    "view:employees",
    "create:employees",
    "edit:employees",
    "delete:employees",
    "view:departments",
    "create:departments",
    "edit:departments",
    "view:teams",
    "create:teams",
    "edit:teams",
    "view:projects",
    "create:projects",
    "edit:projects",
    "view:tasks",
    "create:tasks",
    "edit:tasks",
    "delete:tasks",
    "edit:task_status",
    "view:reports",
    "view:audit_logs",
    "view:settings",
    "export:data",
  ],
  MANAGER: [
    "view:dashboard",
    "view:employees",
    "create:employees",
    "edit:employees",
    "delete:employees",
    "view:departments",
    "view:teams",
    "view:projects",
    "view:tasks",
    "create:tasks",
    "edit:tasks",
    "delete:tasks",
    "edit:task_status",
    "view:reports",
    "view:audit_logs",
    "view:settings",
    "export:data",
  ],
  EMPLOYEE: [
    "view:dashboard",
    "view:employees",
    "view:tasks",
    "edit:task_status",
  ],
  VIEWER: [
    "view:dashboard",
    "view:employees",
    "view:tasks",
    "view:projects",
    "view:reports",
  ],
};

export function hasPermission(role: UserRole, permission: Permission): boolean {
  const permissions = ROLE_PERMISSIONS[role];
  return permissions ? permissions.includes(permission) : false;
}
